export const Route = {
  //bottomTab
  MAIN: "MAIN",

  //LOGIN
  LOGIN: "LOGIN",

  //STACKS
  HOME_STACK: "HOMESTACK",
  ACCOUNT_STACK: "ACCOUNTSTACK",
  ONBOARDING_STACK: "ONBOARDING",
  REGISTRATION_STACK: "REGISTRATION",
  EARNING_STACK: "EARNINGSTACK",

  //ONBOARDING
  ONBOARDING: "ONBOARDING",
  NUMBERVERFICATION: "NUMBERVERFICATION",
  OTPVERFICATION: "OTPVERFICATION",
  DRIVERREGISTRATION: "DRIVERREGISTRATION",

  //
  WELCOME: "WELCOME",
  VEHICLETYPE: "VEHICLETYPE",
  VEHICLEINSPECION: "VEHICLEINSPECTION",
  UPLOADDOCUMENT: "UPLOADDOCUMENT",
  PROFILESETTING:"PROFILESETTING",
  EDITPROFILE:'EDITPROFILE',
  SETLANGUAGE:"SETLANGUAGE",

  //vehicle
  VEHICLESELFINSPECION: "VEHICLESELFINSPECTION",
  VEHICLEQUIZ: "VEHICLEQUIZ",
  APPLICATIONSUBMITTED: "APPLICATIONSUBMITTED",

  //home
  HOME: "HOME",
  CLIENTLOCATION: "CLIENTLOCATION",

  //earning
  EARNING: "EARNING",
  EARNINGHISTORY: "EARNINGHISTORY",
  SUBSCRIPTIONPLAN: "SUBSCRIPTIONPLAN",
  WALLET: "WALLET",
  ALLORDERS: "ALLORDERS",
  ORDERDETAILS: "ORDERDETAILS",
  INCENTIVES: "INCENTIVES",

  //inspection
  EXTERIORINSPECTION: "EXTERIORINSPECTION",
  INTERIORININSPECTION: "INTERIORINSPECTION",
  PHOTOVERIFICATION: "PHOTOVERFICATION",
  VIDEOVERIFICATION: "VIDEOVERIICATION",
};
