export const Route = {
  //bottomTab
  MAIN: "MAIN",

  //LOGIN
  LOGIN: "LOGIN",

  //STACKS
  HOME_STACK: "HOMESTACK",
  ACCOUNT_STACK: "ACCOUNTSTACK",
  ONBOARDING_STACK: "ONBOARDING",
  REGISTRATION_STACK: "REGISTRATION",

  //ONBOARDING
  ONBOARDING: "ONBOARDING",
  NUMBERVERFICATION: "NUMBERVERFICATION",
  OTPVERFICATION: "OTPVERFICATION",
  DRIVERREGISTRATION: "DRIVERREGISTRATION",

  //
  WELCOME: "WELCOME",
  VEHICLETYPE: "VEHICLETYPE",
  VEHICLEINSPECION: "VEHICLEINSPECTION",
  UPLOADDOCUMENT: "UPLOADDOCUMENT",

  //vehicle
  VEHICLESELFINSPECION: "VEHICLESELFINSPECTION",
  VEHICLEQUIZ: "VEHICLEQUIZ",
  APPLICATIONSUBMITTED: "APPLICATIONSUBMITTED",

  //home
  HOME:"HOME",
  CLIENTLOCATION:"CLIENTLOCATION"
};
