export const Route = {
  //bottomTab
  MAIN: "MAIN",

  //LOGIN
  LOGIN: "LOGIN",

  //STACKS
  HOME_STACK: "HOMESTACK",
  ACCOUNT_STACK: "ACCOUNTSTACK",
  ONBOARDING_STACK: "ONBOARDING",
  REGISTRATION_STACK: "REGISTRATION",
  EARNING_STACK: "EARNINGSTACK",
  PERFORMANCE_STACK: "PERFORMANCESTACK",

  //ONBOARDING
  ONBOARDING: "ONBOARDING",
  NUMBERVERFICATION: "NUMBERVERFICATION",
  OTPVERFICATION: "OTPVERFICATION",
  DRIVERREGISTRATION: "DRIVERREGISTRATION",

  //
  WELCOME: "WELCOME",
  VEHICLETYPE: "VEHICLETYPE",
  VEHICLEINSPECION: "VEHICLEINSPECTION",
  UPLOADDOCUMENT: "UPLOADDOCUMENT",
  PROFILESETTING: "PROFILESETTING",
  EDITPROFILE: "EDITPROFILE",
  SETLANGUAGE: "SETLANGUAGE",

  //vehicle
  VEHICLESELFINSPECION: "VEHICLESELFINSPECTION",
  VEHICLEQUIZ: "VEHICLEQUIZ",
  APPLICATIONSUBMITTED: "APPLICATIONSUBMITTED",

  //home
  HOME: "HOME",
  CLIENTLOCATION: "CLIENTLOCATION",
  SHAREDRIDELOCATION: "SHAREDRIDELOCATION",
  DRIVERCHATSCREEN: "DRIVERCHATSCREEN",
  OTPSTARTRIDE:"OTPSTARTRIDE",
  //drawerScreen
  INBOX: "INBOX",
  MYACCOUNT: "MYACCOUNT",
  APPSETTING: "APPSETTING",
  SAVEDADDRESS: "SAVEDADDRESS",
  //earning
  EARNING: "EARNING",
  EARNINGHISTORY: "EARNINGHISTORY",
  SUBSCRIPTIONPLAN: "SUBSCRIPTIONPLAN",
  WALLET: "WALLET",
  ALLORDERS: "ALLORDERS",
  ORDERDETAILS: "ORDERDETAILS",
  INCENTIVES: "INCENTIVES",

  //inspection
  EXTERIORINSPECTION: "EXTERIORINSPECTION",
  INTERIORININSPECTION: "INTERIORINSPECTION",
  PHOTOVERIFICATION: "PHOTOVERFICATION",
  VIDEOVERIFICATION: "VIDEOVERIICATION",

  //performance
  PERFORMANCE: "PERFORMANCE",
  INBOX: "INBOX",
  DOCUMENT: "DOCUMENT",
  RIDEHISTORY: "RIDEHISTORY",
  SCHEDULEPICKUP: "SCHEDULEPICKUP",
  EDITUSERPROFILE: "EDITUSERPROFILE",
};
